@echo off
REM ===========================================================================
REM commit-build.bat - Commit a primary build delivery and tag it.
REM
REM Usage:   commit-build.bat ^<slug^>
REM Example: commit-build.bat blackjack-trainer
REM
REM Stages runs\^<slug^>\, commits with [run:^<slug^>] prefix, tags
REM delivery/^<slug^>, and pushes commit + tag to origin/main.
REM
REM Per the git-integration-proposal convention. The slug must match an
REM existing directory under runs\. Scope rule: this commit only touches
REM files inside runs\^<slug^>\ -- nothing else. This is what keeps
REM `git filter-repo --path runs/^<slug^>/` clean at promotion time.
REM
REM Production location: project root (graduated from scripts\draft\ on 2026-05-15
REM after retroactive-bootstrap.bat validated the same git-tag pattern end-to-end).
REM ===========================================================================

setlocal
cd /d "%~dp0"
set "SLUG=%~1"

if "%SLUG%"=="" goto :usage
if not exist "runs\%SLUG%" (
    echo *** runs\%SLUG% does not exist. ***
    exit /b 1
)

REM Refuse if delivery tag already exists - prevents accidental double-commits.
git rev-parse "delivery/%SLUG%" >nul 2>nul
if not errorlevel 1 (
    echo *** delivery/%SLUG% already exists. This appears to be a re-delivery. ***
    echo Use commit-step.bat for additional-step revisions on an existing build.
    exit /b 1
)

echo === Clearing any stuck git lock files ===
if exist .git\index.lock del /f /q .git\index.lock
if exist .git\config.lock del /f /q .git\config.lock
if exist .git\HEAD.lock del /f /q .git\HEAD.lock

echo === Staging runs\%SLUG% ===
git add "runs\%SLUG%" || goto :err

echo === Showing what will be committed ===
git status --short

echo.
echo === Committing primary delivery ===
git commit -m "[run:%SLUG%] delivery: final artifact written" -m "Primary delivery commit for %SLUG%. Generated by commit-build.bat per the git-integration-proposal convention (commits scoped strictly to runs/%SLUG%/). Tag delivery/%SLUG% applied next." || goto :err

echo === Tagging delivery/%SLUG% ===
git tag -a "delivery/%SLUG%" -m "Primary delivery: %SLUG%" || goto :err

echo === Pushing commit and tag ===
git push --follow-tags origin main || goto :err

echo.
echo === DONE -- %SLUG% delivered, tagged, pushed ===
pause
exit /b 0

:usage
echo Usage: commit-build.bat ^<slug^>
echo   Example: commit-build.bat blackjack-trainer
exit /b 1

:err
echo.
echo *** A step failed. See output above. ***
pause
exit /b 1
