@echo off
REM ===========================================================================
REM snapshot-run.bat - Commit an in-progress build's runs/ folder.
REM
REM Usage:   snapshot-run.bat ^<slug^>
REM Example: snapshot-run.bat closest-liquor-store
REM
REM Stages runs\^<slug^>\ and commits it with a [run:^<slug^>] snapshot prefix,
REM scoped strictly to that folder, then rebases on origin/main and pushes.
REM
REM Why this exists: deploy-session.bat commits architecture/, codex/ and
REM repo-root scripts -- but never runs/. The CI aggregator rebuilds the
REM dashboard data layer from committed runs/ on every push, so any build
REM whose runs\^<slug^>\ folder is not committed is dropped from the dashboard
REM index on the next push. This script commits that folder for a build that
REM is still in progress, so it appears on (and stays on) the dashboard.
REM
REM This is NOT a delivery. It applies no delivery/^<slug^> tag. Use
REM commit-build.bat for the tagged delivery commit once the build finishes,
REM and commit-step.bat for additional-step revisions after delivery.
REM
REM Scope rule: this commit touches only files under runs\^<slug^>\ -- the
REM same discipline commit-build.bat keeps, so `git filter-repo --path
REM runs/^<slug^>/` stays clean at promotion time.
REM ===========================================================================

setlocal
cd /d "%~dp0"
set "PATHEXT=.COM;.EXE;.BAT;.CMD"
set "SLUG=%~1"

if "%SLUG%"=="" goto :usage
if not exist "runs\%SLUG%" (
    echo *** runs\%SLUG% does not exist -- nothing to snapshot. ***
    echo The build must have produced substrate before it can be snapshotted.
    pause
    exit /b 1
)

echo === Clearing any stuck git lock files ===
if exist .git\index.lock del /f /q .git\index.lock
if exist .git\config.lock del /f /q .git\config.lock
if exist .git\HEAD.lock del /f /q .git\HEAD.lock

echo === Staging runs\%SLUG% ===
git add "runs\%SLUG%" || goto :err

echo === Checking whether anything changed ===
git diff --cached --quiet -- "runs/%SLUG%"
if not errorlevel 1 (
    echo No new or changed files under runs\%SLUG% -- already up to date.
    echo Nothing to snapshot.
    pause
    exit /b 0
)

echo === What will be committed ===
git diff --cached --stat -- "runs/%SLUG%"

echo.
echo === Committing snapshot ===
git commit -m "[run:%SLUG%] snapshot: in-progress build substrate" -m "Point-in-time snapshot of an in-progress build's runs/ folder, committed so the dashboard data layer -- which the CI aggregator rebuilds from runs/ on every push -- keeps the run. Not a delivery: no delivery/ tag is applied. Generated by snapshot-run.bat. Scope: this commit touches only runs/%SLUG%/." || goto :err

echo === Rebasing on origin/main ===
git pull --rebase --autostash -X ours origin main || goto :err

echo === Pushing ===
git push origin main || goto :err

echo.
echo === DONE -- runs\%SLUG% snapshotted and pushed ===
echo The CI aggregator will pick it up; the dashboard will show it shortly.
git log --oneline -3
pause
exit /b 0

:usage
echo Usage: snapshot-run.bat ^<slug^>
echo   Example: snapshot-run.bat closest-liquor-store
exit /b 1

:err
echo.
echo *** A step failed. See output above. ***
pause
exit /b 1
